---
title: "Tplyr table module"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Tplyr table module}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This guide provides a detailed overview of the `mod_Tplyr_table` module and its features. It is meant to provide guidance to App Creators on creating Apps in DaVinci using the `mod_Tplyr_table` module.

Walk-throughs for sample app creation using the module are also included
to demonstrate the various module specific features.


`mod_Tplyr_table` serves as a wrapper for generating interactive summary tables. The module leverages Tplyr’s metadata extraction functionality to offer traceability from the summary tables back to the source listing. The metadata from each result cell is mapped to a click event, which generates the source listing.

# Features

`mod_Tplyr_table` features the following outputs:

- A table created using `Tplyr` package.
- filtered listing from the selected cell of the table.

**Mandatory Arguments**

-   `module_id` : A unique identifier of type character for the module

- `tplyr_table_fn`: Function which encapsulates the Tplyr table object code. Additionally add the datasets as function arguments. 

- `build_fn`: Functions which encapsulates table building code. It takes Tplyr tab object as an argument. 

**(Optional) Arguments for listing customization**

The module uses `dv.listings` for showing drill-down listing data. Therefore additional arguments can be provided for further customization.

- `subjid_var`: Column corresponding to subject ID. Default value is 'USUBJID'

- `default_vars`: A list of character vectors which contain the variable names to be displayed as default per dataset. Named according to the `dataset_names.` If `NULL`, the first six variables are displayed for each dataset.

- `pagination`: boolean indicating if pagination should be activated, or `NULL` 

- `intended_use_label`:  Either a string indicating the intended use for export, or NULL. 

- `receiver_id`: To enable switching to another DaVinci module, set `receiver_id` to the module ID of your counterpart module.

# Example

A simple example, understanding of tab fun and build fun, default build fun. Example with jumping feature. 

<!-- Put the mock Tplyr table code here -->

 
